# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cameraExample' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for cameraExample
    pod 'CameraCloudClient', :path => '../'
    pod 'MJExtension'

  target 'cameraExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cameraExampleUITests' do
    # Pods for testing
  end

end
